# Generated by Django 3.1 on 2023-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seigikou_portal_app', '0004_auto_20230902_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
