# Generated by Django 3.1 on 2024-02-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seigikou_portal_app', '0005_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kouen',
            name='koushi',
            field=models.CharField(max_length=256),
        ),
    ]
