# Generated by Django 3.1 on 2024-02-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seigikou_portal_app', '0006_auto_20240201_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='kouen',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
