# Generated by Django 4.0.6 on 2024-02-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seigikou_portal_app', '0006_alter_account_id_alter_bumon_id_alter_event_id_and_more'),
        ('seigikou_portal_app', '0007_kouen_company'),
    ]

    operations = [
    ]
